### PR TITLE
add geology data

### PR DESCRIPTION
**Pull request by CovMat**

### CODE REVIEW

**Comment by seisman** [comment]
Please don't add files directly to this repository without reviewing.

**Comment by CovMat** [comment]
Sorry. no next time.

**Comment by core-man** [comment]
Please also submit an issue first if necessary since now the project is a teamwork.

**Comment by seisman** [comment]
I don't think the data is good enough to be included in the repository. I will do a force push to fully remove the data from the repository, since the data is too large.

**Pull request merged**
